name: Build AdvCAD Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake g++ libc6-dev libstdc++6

    - name: Build AdvCAD
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Build Debian package
      run: |
        ./build_deb.sh

    - name: Upload package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: advcad-deb-package
        path: advcad_*.deb

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: advcad_*.deb
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}